//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.11 at 10:57:12 AM YEKT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://interfaces.soap.ru", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.soap.interfaces;
